### ISSUE TITLE
Why exceptions are caught while by `pTap`?

### ISSUE THREAD

**Issue by michalstocki** [sindresorhus/p-tap#3]
The existing implementation causes the following issue:
```javascript
const getA = () => Promise.resolve('a');
const receiveAndTrow = (a) => throw new Error('');
const receiveAndDoOtherThing = (a) => console.log(a)

getA()
  .then(pTap((a) => throw new Error('')))
  .then((a) => {
    // expected the function to NOT be called due to the error
  })
  .catch((e) => {
    // this is never called while expected to be called.
    console.error('error occurred', e);
  });
```
That's because `ret` is given as a second argument to the `then`:
```javascript
	const ret = () => val;
	return Promise.resolve(val).then(fn).then(ret, ret);
```
Why have you decided to catch (and silence) the exceptions?

**Comment by sindresorhus** [comment]
The point of `pTap` is to tap into a promise chain *without affecting it*. Per description:

> Tap into a promise chain without affecting its value or state

And docs:

> Any return value or exception is ignored.

---

I'm curious, what's your use-case for needing this?

**Comment by michalstocki** [comment]
@sindresorhus thanks for the fast response! Yes, I know that this behavior is "by design", but I'm curious what's the profit from having the errors hidden. In my case I treat the error handling seriously. I have several steps of my operation which receives a common input data and return an empty promise:
```javascript
getInputData()
  .then(pTap(stepA))
  .then(pTap(stepB))
  .then(pTap(stepC))
  .then(() => console.log('all done'));
  .catch((e) => console.error('something went wrong', e));
```
And I expected to have a one place where I catch errors. Now, I'm not able to catch any.

**Comment by sindresorhus** [comment]
Thanks for your patience and for bringing it up. I've been thinking about this for a while and you're right. It should never silently ignore rejections. My original thinking was that `tap` a nice way to be able to do stuff without affecting the chain at all, but I now come to realize even if you use `tap` for just some unimportant helpers, you would still want to know if they fail and it's better to fail than to be silent. So let's change this.

**Comment by VamshiKrishnaAlladi** [comment]
Hi @sindresorhus, I've raised a PR #4 fixing this concern. Please review and merge it. Thanks.
